name: 'Auto Assign Reviewers'
on:
  pull_request:
    types: [ready_for_review]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto_assign_reviewers.yml'